CREATE TABLE hotnews (
  id INT(11) NOT NULL AUTO_INCREMENT,
  title VARCHAR(255) NOT NULL,
  link VARCHAR(255) NOT NULL,
  description TEXT NOT NULL,
  pubDate DATETIME NOT NULL,
  PRIMARY KEY (id)
);
